apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        role: {{ .Release.Name }}
        environment: {{ .Values.environment }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          volumeMounts:
            - name: {{ .Release.Name }}-persistent-storage
              mountPath: {{ .Values.deployment.mountPath }}
          env:
            - name: PGDATA
              value: {{ .Values.deployment.mountPath }}/pgdata
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.dbName }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.userName }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.dbPassword }}
          {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.deployment.storageClass | quote }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi